cd /d %~dp0

copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECIfc.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECKernel.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AITCivilAddin.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AIT3DEXPAppHelpForCommands.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECAlignmentHNetworkWorkshop.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECAlignmentNLS.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECAlignmentTestNLS.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECDataExchangeOutput.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECDrainageAlignmentHWorkshop.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECDrainageAlignmentVWorkshop.CATNls  .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECIfc.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AECKernel.CATNls  .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\AITCivilAddin.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCeg2DConnectHorizontalCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCeg3DAlignmentChooserCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignment3DCompassPlayerCusto.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignment3DPlayerCustoCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignment3DPointCmd.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignment3DPointUICtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentConnectCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentDrawing.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentDrawingTableCmd.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentFixErrorCmd.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentHInitializationCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentSpecificationsCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentSweepUICtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentUICtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentUIServices.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentVisualizationCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegCCPError.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegCheckerCriteriaSelectionCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegControlImpactPreferencesCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegCutAndFillUICtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegPLMPlayCompassCmd.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegRoadDesignCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegRoadDesignNls.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegRoadLinearStretchCmd.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegRoadLinearStretchNls.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegSubgradeCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegSubgradeDesignNls.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegSubgradeSurfaceCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegTopoCheckerPanelCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivBridge3DUIHelpForCommands.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilEng3DModelingWorkbenchHelpForCommands.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilEngAlignmentError.CATNls  .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilEngAlignmentUI.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilEngAlignmentWorkbenchHelpForCommands.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilReportManager.CATNls  .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilUIXMLReporterCtl.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\CATPackageAECPackageFunctions.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\DELPointCloudBBWidget.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\DELPointCloudElementsNLS.CATNls .\3ds\B426
copy "C:\Program Files\Dassault Systemes\B426_Cloud\win_b64\resources\msgcatalog\Simplified_Chinese"\DELPointCloudUIHelpForCommands.CATNls .\3ds\B426
