copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECIfc.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECKernel.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AITCivilAddin.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AIT3DEXPAppHelpForCommands.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECAlignmentHNetworkWorkshop.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECAlignmentNLS.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECAlignmentTestNLS.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECDataExchangeOutput.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECDrainageAlignmentHWorkshop.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECDrainageAlignmentVWorkshop.CATNls  D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECIfc.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AECKernel.CATNls  D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\AITCivilAddin.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCeg2DConnectHorizontalCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCeg3DAlignmentChooserCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignment3DCompassPlayerCusto.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignment3DPlayerCustoCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignment3DPointCmd.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignment3DPointUICtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentConnectCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentDrawing.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentDrawingTableCmd.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentFixErrorCmd.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentHInitializationCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentSpecificationsCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentSweepUICtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentUICtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentUIServices.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegAlignmentVisualizationCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegCCPError.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegCheckerCriteriaSelectionCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegControlImpactPreferencesCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegCutAndFillUICtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegPLMPlayCompassCmd.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegRoadDesignCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegRoadDesignNls.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegRoadLinearStretchCmd.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegRoadLinearStretchNls.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegSubgradeCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegSubgradeDesignNls.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegSubgradeSurfaceCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCegTopoCheckerPanelCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivBridge3DUIHelpForCommands.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilEng3DModelingWorkbenchHelpForCommands.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilEngAlignmentError.CATNls  D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilEngAlignmentUI.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilEngAlignmentWorkbenchHelpForCommands.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilReportManager.CATNls  D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATCivilUIXMLReporterCtl.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\CATPackageAECPackageFunctions.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\DELPointCloudBBWidget.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\DELPointCloudElementsNLS.CATNls D:\010_Gitee\catia-language\3ds\B424
copy "C:\Program Files\Dassault Systemes\B424\win_b64\resources\msgcatalog\Simplified_Chinese"\DELPointCloudUIHelpForCommands.CATNls D:\010_Gitee\catia-language\3ds\B424
